language: node_js
node_js:
  - 0.10.0
env:
  global:
    - SAUCE_USERNAME: ReMarkdown
    - SAUCE_ACCESS_KEY: b9735d6f-48e0-4aac-99ed-cc12f523eeaf
before_install:
  - npm install -g bower
install:
  - bower install
  - npm install
script: node node_modules/intern/runner.js config=tests/intern

